aws_region="eu-central-1"
s3_bucket="dror-avinun-bucket"
s3_key="pg_cron_lambda.zip"

my_prefix="drordel51"
my_vpc="vpc-42096429"
my_subnets="subnet-a950c2d4\\,subnet-7759323a"
my_schedule="rate(1 hour)"
my_db_endpoint="rdsrnd.example.com"
my_db_port="5432"
my_database="mydb"
my_dbuser="mydb"
my_dbpassword="mydb"
my_query="SELECT MERGE_INTO_TERMINAL_ACTIVE()\,SELECT REFRESH_TERMINAL_CNT()\,SELECT CLEAN_PURGE_UPD_FILE_TRACK()"

tag_owner="Dror Avinun"
tag_team="Architects"