aws_region="eu-central-1"
s3_bucket="dror-avinun-bucket"
s3_key="pg_cron_lambda.zip"

my_prefix="drordel49"
my_vpc="vpc-0b0fa98e6f5394a83"
my_subnets="subnet-06fbcaf35b65cd731\\,subnet-0a77a9930f159ffb6"
#my_schedule="rate\(1 hour\)"
my_db_endpoint="myrds.example.com"
my_db_port="5432"
my_database="mydb"
my_dbuser="mydbuser"
my_dbpassword="mydbpassword"
#my_query="[{\"q\":\"SELECT MERGE_INTO_TERMINAL_ACTIVE()\"},{\"q\":\"SELECT REFRESH_TERMINAL_CNT()\"},{\"q\":\"SELECT CLEAN_PURGE_UPD_FILE_TRACK()\"}]"

tag_owner="Dror Avinun"
tag_team="Architects"